import Image from 'next/image'
import Layout from '@/components/HomePage/Layout'
import Landing from '@/components/HomePage/Landing'

export const metadata = {
  title: 'JIJI rentals',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <Layout>
    <Landing/>
      </Layout>
         </main>
  )
}
